version: '3'
services:
  server:
    build: .
    ports:
      - 80:8080
      - 9222:9222
    command: npm run debug
    volumes:
      - ./dist_server:/app/dist_server
    environment:
      - PORT:8080