version: '3'
services:
  mongo:
    image: mongo:3.6.8-stretch
    ports:
      - 27017:27017

  server:
    build: .
    ports:
      - 3000:3000
      - 9222:9222
    command: npm run __debug
    depends_on:
      - mongo
    volumes:
      - ./dist_server:/app/dist_server
      - ./dist_client:/app/dist_client
      - ./client/public:/app/public
    environment:
      - PORT:3000
