version: '3'
services:
  server:
    build: .
    ports:
      - "8080:8080"
      - "9222:9222"
    command: npm run debug
    volumes:
      - ./dist_server:/app/server
    environment:
      - PORT:8080